version: "3.9"
services:
  bot:
    build: .
    depends_on:
      - db
    networks:
      - bot-db
    environment:
      DEV: "true"
  db:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
    networks:
      - bot-db
    ports:
      - 27017:27017
networks:
  bot-db: {}
